### ISSUE TITLE
Error during New-AGMLibVM

### ISSUE THREAD

**Issue by matt63** [Actifio/AGMPowerLib#11]
New-AGMLibVM -imageid 59884072 -vmname matteovm -datastore "IBM-iSCSI-V3700-1" -vcenterid 5552150 -esxhostid 26534616 -mountmode prdm -mapdiskstoallesxhosts false -poweronvm true -volumes '[IBM-FC-V3700] demo-sql-3/demo-sql-3.vmdk' -monitor
InvalidArgument: /Users/mferrari/.local/share/powershell/Modules/AGMPowerLib/0.0.0.23/Public/New-AGMLibVM.ps1:574
Line |
 574 |          $wait = "y"
     |          ~~~~~~~~~~~
     | Cannot convert the "y" value of type "System.String" to type
     | "System.Management.Automation.SwitchParameter".

**Comment by aussiestorblog** [comment]
Fixed in 0.0.0.24
