### ISSUE TITLE
Error during New-AGMLibVM - The term 'Get-AGMFollowJobStatus' is not recognized 

### ISSUE THREAD

**Issue by matt63** [Actifio/AGMPowerLib#12]
PS /Users/mferrari> New-AGMLibVM -imageid 59884072 -vmname matteovm -datastore "IBM-iSCSI-V3700-1" -vcenterid 5552150 -esxhostid 26534616 -mountmode prdm -mapdiskstoallesxhosts false -poweronvm true -volumes '[IBM-FC-V3700] demo-sql-3/demo-sql-3.vmdk' -monitor -wait
InvalidArgument: /Users/mferrari/.local/share/powershell/Modules/AGMPowerLib/0.0.0.23/Public/New-AGMLibVM.ps1:574
Line |
 574 |          $wait = "y"
     |          ~~~~~~~~~~~
     | Cannot convert the "y" value of type "System.String" to type
     | "System.Management.Automation.SwitchParameter".

jobname    : Job_28662677
status     : running
queuedate  : 2020-10-27 22:23:43
startdate  : 2020-10-27 22:23:44
targethost : matteovm

Get-AGMFollowJobStatus: /Users/mferrari/.local/share/powershell/Modules/AGMPowerLib/0.0.0.23/Public/New-AGMLibVM.ps1:607
Line |
 607 |              Get-AGMFollowJobStatus $jobgrab.jobname
     |              ~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AGMFollowJobStatus' is not recognized as the name of a cmdlet, function, script
     | file, or operable program. Check the spelling of the name, or if a path was included, verify that
     | the path is correct and try again.

**Comment by aussiestorblog** [comment]
Fixed in 0.0.0.24
