### ISSUE TITLE
Unrecognized system state option OSType

### ISSUE THREAD

**Issue by kkerr2005** [Actifio/AGMPowerLib#13]
Im trying to recover a streamsnap systemstate image using this command:-

New-AGMLibSystemStateToVM -vcenterid "$($vcenter.id)" -esxhostid "$($esxi.id)" -appid "$($app.id)" -imageid "$($latestimage.id)" -vmname "$($item.vmname)" -datastore "$($item.datastore)" -appname "$($app.appname)"

but getting the following error

{
   "err_code" : 10040,
   "err_message" : "Unrecognized system state option OSType"
}

when running 
Get-AGMImageSystemStateOptions -imageid $latestimage.id -target vmware

I get the following returned:-

@type        : systemStateOptionMetadataRest
name         : CPU
displayname  : CPU (vCPU)
type         : number
description  : Number of CPU
required     : False
multi        : False
defaultvalue : 2
sensitive    : False
category     : system

@type        : systemStateOptionMetadataRest
name         : Memory
displayname  : Memory (GB)
type         : number
description  : Memory in GB
required     : False
multi        : False
defaultvalue : 4
sensitive    : False
category     : system

@type         : systemStateOptionMetadataRest
name          : CloudType
displayname   : Cloud Type
type          : string
description   : Cloud type
required      : True
multi         : False
choices       : {@{name=VMware}}
defaultvalue  : VMware
lastusedvalue : VMware
sensitive     : False

@type       : systemStateOptionMetadataRest
name        : NICInfo
displayname : Network Information
type        : structure
description : VMware NIC Details
required    : True
multi       : True
structure   : {@{name=DHCP; displayname=Use DHCP; type=boolean; description=Use DHCP; required=False; multi=False; defaultvalue=false; lastusedvalue=false; sensitive=False}, 
              @{name=NICNetwork; displayname=Network Name; type=string; description=NIC name; required=False; multi=False; lastusedvalue=Management_VC; sensitive=False}, @{name=NICType; 
              displayname=Type; type=string; description=NIC type; required=False; multi=False; choices=System.Object[]; defaultvalue=VMXNet3; lastusedvalue=VMXNet3; sensitive=False}, 
              @{name=NICIP; displayname=IP Address; type=string; description=NIC IP address; required=False; multi=False; sensitive=False}...}
sensitive   : False

Last Post command seems to show the OSType value being empty

@type      : auditRest
id         : 13285230
href       : https://172.30.219.51/actifio/localaudit/13285230
issuedate  : 2021-01-14 11:26:29
username   : admin
command    : POST https://172.30.219.51/actifio/backup/13278555/mount  Session 65dcddaa {"@type":"mountRest","datastore":"BCA_DR_STORAGE_9","hypervisor":{"id":"1155827"},"mgmtserver":{"id":"
             1155740"},"hostname":"PD-FTP-005","poweronvm":true,"systemstateoptions":[{"name":"CPU","value":"2"},{"name":"Memory","value":"4"},{"name":"OSType","value":""},{"name":"CloudType
             ","value":"VMware"}],"migratevm":false}
ipaddress  : 172.30.219.52
component  : RESTful
status     : 10040
privileged : False

**Comment by kkerr2005** [comment]
removing this line solved it fo rme

[ordered]@{ name = 'OSType'; value = $ostype }

**Comment by aussiestorblog** [comment]
It looks like older System State images don't have OSTYPE field.   Your solution is a simple workaround.   I will add some logic to test for ostype in update 0.0.0.29, since if we have it, it is good to use it.   That branch is uploaded with the change, but I haven't QAd it yet.   Am working on several updates for that release, so once they are all done and tested I will push it to main.   However you can test by downloading branch 0.0.0.29 and manually installing.

**Comment by aussiestorblog** [comment]
Its now in main
